/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mg.eni.app.achat;

import com.eni.gestion_de_pharmacie.entree.Entree;
import com.eni.gestion_de_pharmacie.entree.ModifierEntree;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.postgresql.util.PSQLException;

/**
 *
 * @author erb
 */
public class ModifierAchat extends javax.swing.JDialog {

    private int stock;
    private String mdNum;
    Connection connection;
    ResultSet result;
    PreparedStatement prst;

    public void connect() {
        try {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/gestion_pharmacie", "postgres", "administrator");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void deconnect() {
        try {
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form ajouterMedicament
     */
    public ModifierAchat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Date date = null;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(Achat.dateAchatStatic);
        } catch (ParseException ex) {
            Logger.getLogger(ModifierEntree.class.getName()).log(Level.SEVERE, null, ex);
        }
        dateAchatDateChooser.setDate(date);
        nomClientField.setText(Achat.nomClientStatic);
        nombreSpinner.setValue(Achat.nbrStatic);
    }

    private void stockApresModification() {
        try {
            connect();
            String designMedoc = Achat.medocDesignStatic;
            String numAchatSelected = Achat.numAchatStatic;
            String medocNumStatic = "";
            int sommeAchat = 0;
            prst = connection.prepareStatement("SELECT \"numMedoc\" FROM gp.\"MEDICAMENT\" WHERE design = ?");
            prst.setString(1, designMedoc);
            result = prst.executeQuery();

            while (result.next()) {
                medocNumStatic = result.getString("numMedoc");
                mdNum = result.getString("numMedoc");
            }

            prst = connection.prepareStatement("SELECT COALESCE((SELECT SUM(nbr) FROM gp.\"ACHAT\" WHERE \"medocNum\" = CAST(? AS ulid) AND \"numAchat\" != CAST(? AS ulid)), 0) AS \"sommeAchat\"");
            prst.setString(1, medocNumStatic);
            prst.setString(2, numAchatSelected);
            result = prst.executeQuery();

            while (result.next()) {
                sommeAchat = result.getInt("sommeAchat") + (int) nombreSpinner.getValue();
            }

            prst = connection.prepareStatement("SELECT (COALESCE((SELECT SUM(\"stockEntree\") FROM gp.\"ENTREE\" WHERE \"medocNum\" = CAST(? AS ulid)), 0) - ?) AS stock");
            prst.setString(1, medocNumStatic);
            prst.setInt(2, sommeAchat);
            result = prst.executeQuery();

            while (result.next()) {
                stock = result.getInt("stock");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            deconnect();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        logReinitialiserBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombreSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomClientField = new javax.swing.JTextField();
        dateAchatDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULAIRE DE MODIFICATION DE ACHAT");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGO");

        jLabel3.setFont(new java.awt.Font("Cantarell", 3, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MODIFIER");

        jButton1.setText("Modifier");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Annuler");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        logReinitialiserBtn.setText("Reinitialiser");
        logReinitialiserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logReinitialiserBtnMouseClicked(evt);
            }
        });

        jLabel4.setText("Nombre de médicament à acheter :");

        jLabel6.setText("Nom complet du client :");

        jLabel5.setText("Date de l'achat :");

        nomClientField.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                nomClientFieldComponentShown(evt);
            }
        });

        dateAchatDateChooser.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(218, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(logReinitialiserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateAchatDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomClientField)
                                    .addComponent(nombreSpinner, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(76, 76, 76))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dateAchatDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(nomClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(logReinitialiserBtn))
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            stockApresModification();
            System.out.println("Stock " + stock);

            if (stock >= 0) {
                String dateAchat = new SimpleDateFormat("yyyy-MM-dd").format(dateAchatDateChooser.getDate());
                System.out.println(stock);
                connect();
                prst = connection.prepareStatement("UPDATE gp.\"ACHAT\" SET \"nomClient\" = ?, nbr = ?, \"dateAchat\" = CAST(? AS date) WHERE \"numAchat\" = CAST(? AS ulid)");
                prst.setString(1, nomClientField.getText());
                prst.setInt(2, Integer.parseInt(String.valueOf(nombreSpinner.getValue())));
                prst.setString(3, dateAchat);
                prst.setString(4, Achat.numAchatStatic);
                int result1 = prst.executeUpdate();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(this, "Modification de l'achat réussi!", "MODIFICATION D'ACHAT", 1);
                    try {
                        connect();
                        String sql = "SELECT (COALESCE((SELECT SUM(\"stockEntree\") FROM gp.\"ENTREE\" WHERE \"medocNum\" = CAST(? AS ulid)), 0)"
                                + " - COALESCE((SELECT SUM(nbr) FROM gp.\"ACHAT\" WHERE \"medocNum\" = CAST(? AS ulid)), 0)) AS \"stockApresModification\"";
                        prst = connection.prepareStatement("UPDATE gp.\"MEDICAMENT\" SET stock = (" + sql + ") WHERE \"numMedoc\" = CAST(? AS ulid)");
                        prst.setString(1, mdNum);
                        prst.setString(2, mdNum);
                        prst.setString(3, mdNum);
                        prst.executeUpdate();
                    } catch (Exception e) {
                        e.printStackTrace();
                    } finally {
                        deconnect();
                    }
                    Achat.staticTableauActualisation();
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "!!Le stock de ce médicament dans la table MEDICAMENT deviendra négatif si vous insérez ce nombre de medicament acheté!!", "MODIFICATION REFUSÉE", 1);
            }

        } catch (PSQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur de requête SQL", 1);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            deconnect();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logReinitialiserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logReinitialiserBtnMouseClicked
        // TODO add your handling code here:
        dateAchatDateChooser.setDate(new Date());
        nomClientField.setText("");
        nombreSpinner.setValue(0);
    }//GEN-LAST:event_logReinitialiserBtnMouseClicked

    private void nomClientFieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nomClientFieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_nomClientFieldComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ModifierAchat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ModifierAchat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ModifierAchat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ModifierAchat.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifierAchat dialog = new ModifierAchat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateAchatDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logReinitialiserBtn;
    private javax.swing.JTextField nomClientField;
    private javax.swing.JSpinner nombreSpinner;
    // End of variables declaration//GEN-END:variables
}
